using HarmonyLib;
using System;
using System.Collections.Generic;
using System.Xml;
using Verse;

namespace Apini
{   //Should consider every defname on save load, and replace old apini names with these new ones provided in the replacement map. Should not touch any defnames except those listed.
    [StaticConstructorOnStartup]
    static class BackCompatibilityInjector
    {
        static BackCompatibilityInjector()
        {
            Traverse.Create(typeof(BackCompatibility)).Field<List<BackCompatibilityConverter>>("conversionChain").Value.Add(new BackCompatibilityConverter_Apini());
        }
    }
    public class BackCompatibilityConverter_Apini : BackCompatibilityConverter
    {
        //Begin Def Replacement map
        readonly List<List<string>> defReplacements = new List<List<string>>{
new List<string>{"EmptyVat_V", "ApiniEmptyVat_V"},
new List<string>{"EmptyVat_W", "ApiniEmptyVat_W"},
new List<string>{"EmptyVat_R", "ApiniEmptyVat_R"},
new List<string>{"EmptyVat_B", "ApiniEmptyVat_B"},
new List<string>{"EmptyVat_M", "ApiniEmptyVat_M"},
new List<string>{"EmptyVat_E", "ApiniEmptyVat_E"},
new List<string>{"EmptyVat_F", "ApiniEmptyVat_F"},
new List<string>{"EmptyHoneyCapsule", "ApiniEmptyHoneyCapsule"},
new List<string>{"TakeHoneyOutOfFermentingVat", "ApiniTakeHoneyOutOfFermentingVat"},
new List<string>{"FillVat_V", "ApiniFillVat_V"},
new List<string>{"FillVat_W", "ApiniFillVat_W"},
new List<string>{"FillVat_R", "ApiniFillVat_R"},
new List<string>{"FillVat_B", "ApiniFillVat_B"},
new List<string>{"FillVat_M", "ApiniFillVat_M"},
new List<string>{"FillVat_E", "ApiniFillVat_E"},
new List<string>{"FillVat_F", "ApiniFillVat_F"},
new List<string>{"FillHoneyCapsule", "ApiniFillHoneyCapsule"},
new List<string>{"FillHoneyVat", "ApiniFillHoneyVat"},
new List<string>{"HoneyMaker", "ApiniHoneyMaker"},
new List<string>{"BeeswaxMaking", "ApiniBeeswaxMaking"},
new List<string>{"Apini_PetBase", "ApiniPetBase"},
new List<string>{"Alien_Bee", "ApiniBeelien"},
new List<string>{"PollenBall_V", "ApiniPollenBall_V"},
new List<string>{"PollenBall_W", "ApiniPollenBall_W"},
new List<string>{"PollenBall_R", "ApiniPollenBall_R"},
new List<string>{"PollenBall_B", "ApiniPollenBall_B"},
new List<string>{"PollenBall_M", "ApiniPollenBall_M"},
new List<string>{"PollenBall_E", "ApiniPollenBall_E"},
new List<string>{"PollenBall_F", "ApiniPollenBall_F"},
new List<string>{"PollenBall", "ApiniPollenBall"},
new List<string>{"PollenBallBase", "ApiniPollenBallBase"},
new List<string>{"PollenBase", "ApiniPollenBase"},
new List<string>{"PlantVigorbloom", "ApiniPlantVigorbloom"},
new List<string>{"PlantWiserbud", "ApiniPlantWiserbud"},
new List<string>{"PlantRushthorn", "ApiniPlantRushthorn"},
new List<string>{"PlantBardsong", "ApiniPlantBardsong"},
new List<string>{"PlantMetalily", "ApiniPlantMetalily"},
new List<string>{"PlantEmberose", "ApiniPlantEmberose"},
new List<string>{"PlantFrostbell", "ApiniPlantFrostbell"},
new List<string>{"PlantDaisyApini", "ApiniPlantDaisy"},
new List<string>{"PlantLavenderApini", "ApiniPlantLavender"},
new List<string>{"Pollen", "ApiniPollen"},
new List<string>{"BaseHemolymph", "ApiniHemolymphBase"},
new List<string>{"WaxcraftBase", "ApiniWaxcraftBase"},
new List<string>{"NectarCraftBulk", "ApiniNectarCraftBulk"},
new List<string>{"NectarCraftBase", "ApiniNectarCraftBase"},
new List<string>{"Nectar_V", "ApiniNectar_V"},
new List<string>{"Nectar_W", "ApiniNectar_W"},
new List<string>{"Nectar_R", "ApiniNectar_R"},
new List<string>{"Nectar_B", "ApiniNectar_B"},
new List<string>{"Nectar_M", "ApiniNectar_M"},
new List<string>{"Nectar_E", "ApiniNectar_E"},
new List<string>{"Nectar_F", "ApiniNectar_F"},
new List<string>{"Nectar", "ApiniNectar"},
new List<string>{"NectarBase", "ApiniNectarBase"},
new List<string>{"InsectBodyPartApitech", "ApiniInsectBodyPartApitech"},
new List<string>{"InsectBodyPartApiniAdvancedBionicsTech", "ApiniInsectBodyPartAdvancedBionicsTech"},
new List<string>{"InsectBodyPartApiniBionicsTech", "ApiniInsectBodyPartBionicsTech"},
new List<string>{"InsectBodyPartApiniProstheticsTech", "ApiniInsectBodyPartProstheticsTech"},
new List<string>{"InsectBodyPartNatural", "ApiniInsectBodyPartNatural"},
new List<string>{"InsectBodyPartBase", "ApiniInsectBodyPartBase"},
new List<string>{"BruteHoneyBuff", "ApiniBruteHoneyBuff"},
new List<string>{"SmartHoneyBuff", "ApiniSmartHoneyBuff"},
new List<string>{"SwiftHoneyBuff", "ApiniSwiftHoneyBuff"},
new List<string>{"SmoothHoneyBuff", "ApiniSmoothHoneyBuff"},
new List<string>{"RoughHoneyBuff", "ApiniRoughHoneyBuff"},
new List<string>{"HotHoneyBuff", "ApiniHotHoneyBuff"},
new List<string>{"CoolHoneyBuff", "ApiniCoolHoneyBuff"},
new List<string>{"Honey_V", "ApiniHoney_V"},
new List<string>{"Honey_W", "ApiniHoney_W"},
new List<string>{"Honey_R", "ApiniHoney_R"},
new List<string>{"Honey_B", "ApiniHoney_B"},
new List<string>{"Honey_M", "ApiniHoney_M"},
new List<string>{"Honey_E", "ApiniHoney_E"},
new List<string>{"Honey_F", "ApiniHoney_F"},
new List<string>{"SpecialHoney", "ApiniSpecialHoney"},
new List<string>{"HoneyBase", "ApiniHoneyBase"},
new List<string>{"NectarCategory", "ApiniNectarCategory"},
new List<string>{"HoneyVat", "ApiniHoneyVat"},
new List<string>{"Vat_V", "ApiniVat_V"},
new List<string>{"Vat_W", "ApiniVat_W"},
new List<string>{"Vat_R", "ApiniVat_R"},
new List<string>{"Vat_B", "ApiniVat_B"},
new List<string>{"Vat_M", "ApiniVat_M"},
new List<string>{"Vat_E", "ApiniVat_E"},
new List<string>{"Vat_F", "ApiniVat_F"},
new List<string>{"VatBase", "ApiniVatBase"},
new List<string>{"HoneyCapsule", "ApiniHoneyCapsule"},
new List<string>{"BeeswaxCandle", "ApiniWaxCandle"},
new List<string>{"HoneycombBed_L", "ApiniHoneycombBed_L"},
new List<string>{"HoneycombBed_S", "ApiniHoneycombBed_S"},
new List<string>{"HoneyWall", "ApiniHoneyWall"},
new List<string>{"InsectBodyPartsApitech", "ApiniInsectBodyPartsApitech"},
new List<string>{"InsectBodyPartsArtificial", "ApiniInsectBodyPartsArtificial"},
new List<string>{"InsectBodyPartsNatural", "ApiniInsectBodyPartsNatural"},
new List<string>{"InsectBodyParts", "ApiniInsectBodyParts"},
new List<string>{"Pawn_Moobee_Death", "Moobee_Pawn_Death"},
new List<string>{"Pawn_Moobee_Wounded", "Moobee_Pawn_Wounded"},
new List<string>{"Pawn_Apini_Wounded", "Apini_Pawn_Wounded"},
new List<string>{"Pawn_Apini_Death", "Apini_Pawn_Death"},
new List<string>{"LostHive", "ApiniScenLostHive"},
new List<string>{"NamerbaseHive", "ApiniNamerbaseHive"},
new List<string>{"NamerFactionHive", "ApiniNamerFactionHive"},
new List<string>{"NamerbaseSwarm", "AzuriNamerbaseSwarm"},
new List<string>{"NamerFactionSwarm", "AzuriNamerFactionSwarm"},
new List<string>{"NamerPersonAzuri", "AzuriNamerPerson"},
new List<string>{"NamerPersonApini", "ApiniNamerPerson"},
new List<string>{"HoneyRefining", "ApiniHoneyRefining"},
new List<string>{"HoneyConditioning", "ApiniHoneyConditioning"},
new List<string>{"Enhance_Leg_Apini", "ApiniEnhance_Leg"},
new List<string>{"Enhance_Arm_Growing_Apini", "ApiniEnhance_Arm_Growing"},
new List<string>{"Enhance_Arm_Apini", "ApiniEnhance_Arm"},
new List<string>{"Enhance_Stomach_Apini", "ApiniEnhance_Stomach"},
new List<string>{"Enhance_Heart_Apini", "ApiniEnhance_Heart"},
new List<string>{"Install_Wing_Warmer_Apini", "ApiniInstall_Wing_Warmer"},
new List<string>{"Install_Wing_Breezer_Apini", "ApiniInstall_Wing_Breezer"},
new List<string>{"Install_Wing_Aerator_Apini", "ApiniInstall_Wing_Aerator"},
new List<string>{"Install_Proboscis_Enhancement_Apini", "ApiniInstall_Proboscis_Enhancement"},
new List<string>{"Install_Crusher_Mandibles_Apini", "ApiniInstall_Crusher_Mandibles"},
new List<string>{"Install_Songstress_Mandibles_Apini", "ApiniInstall_Songstress_Mandibles"},
new List<string>{"Install_Monarch_Mandibles_Apini", "ApiniInstall_Monarch_Mandibles"},
new List<string>{"Enhance_Antenna_Apini", "ApiniEnhance_Antenna"},
new List<string>{"Enhance_Eye_Apini", "ApiniEnhance_Eye"},
new List<string>{"Enhance_Brain_Apini", "ApiniEnhance_Brain"},
new List<string>{"InstallBionicAdvancedAntenna_Apini", "ApiniInstallBionicAdvancedAntenna"},
new List<string>{"InstallBionicAntenna_Apini", "ApiniInstallBionicAntenna"},
new List<string>{"InstallProstheticAntenna_Apini", "ApiniInstallProstheticAntenna"},
new List<string>{"InstallAdvancedBionicWing_Apini", "ApiniInstallAdvancedBionicWing"},
new List<string>{"InstallBionicWing_Apini", "ApiniInstallBionicWing"},
new List<string>{"InstallProstheticWing_Apini", "ApiniInstallProstheticWing"},
new List<string>{"InstallInsectLeg_Apini", "ApiniInstallInsectLeg"},
new List<string>{"InstallInsectArm_Apini", "ApiniInstallInsectArm"},
new List<string>{"InstallInsectWing_Apini", "ApiniInstallInsectWing"},
new List<string>{"InstallHoneyStomach_Apini", "ApiniInstallHoneyStomach"},
new List<string>{"InstallInsectMouth_Apini", "ApiniInstallInsectMouth"},
new List<string>{"InstallInsectHeart_Apini", "ApiniInstallInsectHeart"},
new List<string>{"InstallInsectAntenna_Apini", "ApiniInstallInsectAntenna"},
new List<string>{"InstallArchotechEye_Apini", "ApiniInstallArchotechEye"},
new List<string>{"InstallBionicEye_Apini", "ApiniInstallBionicEye"},
new List<string>{"InstallDenture_Apini", "ApiniInstallDenture"},
new List<string>{"InstallPowerClaw_Apini", "ApiniInstallPowerClaw"},
new List<string>{"InstallBionicHeart_Apini", "ApiniInstallBionicHeart"},
new List<string>{"InstallSimpleProstheticHeart_Apini", "ApiniInstallSimpleProstheticHeart"},
new List<string>{"InstallBionicStomach_Apini", "ApiniInstallBionicStomach"},
new List<string>{"InstallArchotechArm_Apini", "ApiniInstallArchotechArm_Apini"},
new List<string>{"InstallSimpleProstheticArm_Apini", "ApiniInstallSimpleProstheticArm"},
new List<string>{"InstallArchotechLeg_Apini", "ApiniInstallArchotechLeg_Apini"},
new List<string>{"InstallBionicLeg_Apini", "ApiniInstallBionicLeg"},
new List<string>{"InstallSimpleProstheticLeg_Apini", "ApiniInstallSimpleProstheticLeg"},
new List<string>{"InstallPegLeg_Apini", "ApiniInstallPegLeg"},
new List<string>{"SurgeryAugment", "ApiniSurgeryAugment"},
new List<string>{"SurgeryApini", "ApiniSurgery"},
new List<string>{"CreateReflexEnhancement_Apini", "ApiniCreateReflexEnhancement"},
new List<string>{"CreateGathererFrontLeg_Apini", "ApiniCreateGathererFrontLeg"},
new List<string>{"CreateProboscisEnhancement_Apini", "ApiniCreateProboscisEnhancement"},
new List<string>{"CreateNeuroenhancer_Apini", "ApiniCreateNeuroenhancer"},
new List<string>{"CreateSignalReceptor_Apini", "ApiniCreateSignalReceptor"},
new List<string>{"CreateOcularEnhancement_Apini", "ApiniCreateOcularEnhancement"},
new List<string>{"CreateRegenerativeEnzymes_Apini", "ApiniCreateRegenerativeEnzymes"},
new List<string>{"CreateDigestiveEnzymes_Apini", "ApiniCreateDigestiveEnzymes"},
new List<string>{"CreateWarmerImplant_Apini", "ApiniCreateWarmerImplant"},
new List<string>{"CreateBreezerImplant_Apini", "ApiniCreateBreezerImplant"},
new List<string>{"CreateAeratorImplant_Apini", "ApiniCreateAeratorImplant"},
new List<string>{"CreateMonarchMandibles_Apini", "ApiniCreateMonarchMandibles"},
new List<string>{"CreateSongstressMandibles_Apini", "ApiniCreateSongstressMandibles"},
new List<string>{"CreateCrusherMandibles_Apini", "ApiniCreateCrusherMandibles"},
new List<string>{"MakeApitechMechanitesMost", "ApiniMakeApitechMechanitesMost"},
new List<string>{"MakeApitechMechanitesMore", "ApiniMakeApitechMechanitesMore"},
new List<string>{"MakeApitechMechanites", "ApiniMakeApitechMechanites"},
new List<string>{"CreateAdvancedBionicAntenna", "ApiniCreateAdvancedBionicAntenna"},
new List<string>{"CreateBionicAntenna", "ApiniCreateBionicAntenna"},
new List<string>{"CreateProstheticAntenna", "ApiniCreateProstheticAntenna"},
new List<string>{"CreateAdvancedBionicWing", "ApiniCreateAdvancedBionicWing"},
new List<string>{"CreateBionicWing", "ApiniCreateBionicWing"},
new List<string>{"CreateProstheticWing", "ApiniCreateProstheticWing"},
new List<string>{"ApiOrganCraft", "ApitechOrganCraft"},
new List<string>{"TakeThingOutOfFermentingVat", "ApiniTakeThingOutOfFermentingVat"},
new List<string>{"FillFermentingVat", "ApiniFillFermentingVat"},
new List<string>{"EnhancedLeg_Apini", "ApiniEnhancedLeg"},
new List<string>{"GathererFrontLeg_Apini", "ApiniGathererFrontLeg"},
new List<string>{"EnhancedArm_Growing_Apini", "ApiniEnhancedArm_Growing"},
new List<string>{"ReflexEnhancement_Apini", "ApiniReflexEnhancement"},
new List<string>{"EnhancedArm_Apini", "ApiniEnhancedArm"},
new List<string>{"DigestiveEnzymes_Apini", "ApiniDigestiveEnzymes"},
new List<string>{"EnhancedStomach_Apini", "ApiniEnhancedStomach"},
new List<string>{"RegenerativeEnzymes_Apini", "ApiniRegenerativeEnzymes"},
new List<string>{"EnhancedHeart_Apini", "ApiniEnhancedHeart"},
new List<string>{"WingWarmer_Apini", "ApiniWingWarmer"},
new List<string>{"EnhancedWing_Warmer_Apini", "ApiniEnhancedWing_Warmer"},
new List<string>{"WingBreezer_Apini", "ApiniWingBreezer"},
new List<string>{"EnhancedWing_Breezer_Apini", "ApiniEnhancedWing_Breezer"},
new List<string>{"WingAerator_Apini", "ApiniWingAerator"},
new List<string>{"EnhancedWing_Aerator_Apini", "ApiniEnhancedWing_Aerator"},
new List<string>{"ProboscisEnhancement_Apini", "ApiniProboscisEnhancement"},
new List<string>{"EnhancedMouth_Eating_Apini", "ApiniEnhancedMouth_Eating"},
new List<string>{"SongstressMandibles_Apini", "ApiniSongstressMandibles"},
new List<string>{"EnhancedMouth_Songstress_Apini", "ApiniEnhancedMouth_Songstress"},
new List<string>{"CrusherMandibles_Apini", "ApiniCrusherMandibles"},
new List<string>{"EnhancedMouth_Crusher_Apini", "ApiniEnhancedMouth_Crusher"},
new List<string>{"MonarchMandibles_Apini", "ApiniMonarchMandibles"},
new List<string>{"SignalReceptor_Apini", "ApiniSignalReceptor"},
new List<string>{"EnhancedMouth_Monarch_Apini", "ApiniEnhancedMouth_Monarch"},
new List<string>{"EnhancedAntenna_Apini", "ApiniEnhancedAntenna"},
new List<string>{"OcularEnhancement_Apini", "ApiniOcularEnhancement"},
new List<string>{"EnhancedEye_Apini", "ApiniEnhancedEye"},
new List<string>{"Neuroenhancer_Apini", "ApiniNeuroenhancer"},
new List<string>{"EnhancedBrain_Apini", "ApiniEnhancedBrain"},
new List<string>{"AdvancedBionicAntenna", "ApiniAdvancedBionicAntenna"},
new List<string>{"BionicAntenna", "ApiniBionicAntenna"},
new List<string>{"ProstheticAntenna", "ApiniProstheticAntenna"},
new List<string>{"AdvancedBionicWing", "ApiniAdvancedBionicWing"},
new List<string>{"BionicWing", "ApiniBionicWing"},
new List<string>{"ProstheticWing", "ApiniProstheticWing"},
new List<string>{"InsectSting", "ApiniInsectSting"},
new List<string>{"HindLegs", "ApiniHindLegs"},
new List<string>{"Thorax", "ApiniInsectThorax"},
new List<string>{"Tarsus", "ApiniInsectTarsus"},
new List<string>{"InsectLeg", "ApiniInsectLeg"},
new List<string>{"Tarsal", "ApiniInsectTarsalClaw"},
new List<string>{"Abdomen", "ApiniInsectAbdomen"},
new List<string>{"Mandible", "ApiniInsectMandible"},
new List<string>{"InsectMouth", "ApiniInsectMouth"},
new List<string>{"InsectAntenna", "ApiniInsectAntenna"},
new List<string>{"Antenna", "ApiniInsectAntenna"},
new List<string>{"InsectHeart", "ApiniInsectHeart"},
new List<string>{"HoneyStomach", "ApiniHoneyStomach"},
new List<string>{"InsectWings", "ApiniInsectWings"},
new List<string>{"InsectWing", "ApiniInsectWing"},
new List<string>{"NecropiniMeatHoneyVat", "NpiniMeatHoneyVat"},
new List<string>{"NecropiniMeatSlurry", "NpiniMeatSlurry"},
new List<string>{"NecropiniMeatHoney", "NpiniMeatHoney"},
new List<string>{"NecropiniPawn", "NpiniPawn"},
new List<string>{"NecropiniSoldier", "NpiniSoldier"},
new List<string>{"NecropiniOverseer", "NpiniOverseer"},
new List<string>{"NecropiniTrader", "NpiniTrader"},
new List<string>{"NecropiniBasic", "NpiniBasic"},
new List<string>{"Necropini_Settings", "Npini_Settings"},
new List<string>{"NecropiniMake_Slurry", "NpiniMake_Slurry"},
new List<string>{"NecropiniMake_BulkSlurry", "NpiniMake_BulkSlurry"},
new List<string>{"BuzzApini", "ApiniBuzz"},
new List<string>{"Apini_Outcast", "ApiniOutcast"}
};
        //End Def Replacement map
        public override bool AppliesToVersion(int majorVer, int minorVer)
        {
            return true;
        }

        public override string BackCompatibleDefName(Type defType, string defName, bool forDefInjections = false, XmlNode node = null)
        {
            foreach (List<string> defmap in defReplacements)
            {
                if (defmap[0] == defName) { return defmap[1]; }
            }
            return null;
        }

        public override Type GetBackCompatibleType(Type baseType, string providedClassName, XmlNode node)
        {
            return null;
        }

        public override void PostExposeData(object obj)
        {
        }



    }
}
